{
 "title": "kpack at scale",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Pods Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(app_info_total)" }
   ]
  },
  {
   "title": "Java 11.0.5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_info_total{java_version=\"11.0.5\"})"
    }
   ]
  },
  {
   "title": "OpenSSL Jun 2019",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_info_total{openssl_version=\"OpenSSL 1.1.1  11 Sep 2018 built on: Thu Jun 20 17:36:28 2019 UTC\"})"
    }
   ]
  },
  {
   "title": "Pods Up-to-date",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(app_info_total{java_version=\"11.0.6\", openssl_version=\"OpenSSL 1.1.1  11 Sep 2018 built on: Tue Nov 12 16:58:35 2019 UTC\"})"
    }
   ]
  },
  {
   "title": "Java 11.0.6",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_info_total{java_version=\"11.0.6\"})"
    }
   ]
  },
  {
   "title": "OpenSSL Nov 2019",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_info_total{openssl_version=\"OpenSSL 1.1.1  11 Sep 2018 built on: Tue Nov 12 16:58:35 2019 UTC\"})"
    }
   ]
  }
 ]
}